### ISSUE TITLE
attribute translation

### ISSUE THREAD

**Issue by M1-K** [nohaelgendy/en-ar-demo#1]
Hi, thanks for this simple i18n implementation. I'm struggling how to translate other than text attributes - for example placeholder="Type here" or value="OK" and so on. Is it possible with your script or not yet?

**Comment by nohaelgendy** [comment]
Thanks @M1-K, you are welcome. Concerning your question, Absolutely! Translating attributes like placeholder and value can be achieved using a similar approach. I will extend the functionality in my script to handle these cases.

**Comment by M1-K** [comment]
❤

will test when I'll have time
